### ISSUE TITLE
Step s2_1 and some files

### ISSUE THREAD

**Issue by 1292917512** [wujsAct/DGCN_EL#1]
The project reported an error in the s2_1 step because it could not find the file'/process/sentid2aNosNoid.txt'  and ’process/entMen2aNosNoid.txt‘. The code did not give the process folder and the files in the folder, and it was not generated by'deep-ed'. Can you share the file “sentid2aNosNoid.txt” and "entMen2aNosNoid.txt"？

**Comment by wujsAct** [comment]
You can find the ''process'' directory from the link: https://drive.google.com/file/d/1oIA3_lytNwE7lVOqojyQxpTkWEmElK8m/view?usp=sharing.

**Comment by 1292917512** [comment]
Thank you for your help, I am currently working hard to run the code.

**Comment by 1292917512** [comment]
Thank you for your help, I am currently working hard to run the code.
