### ISSUE TITLE
step s2_1 and S3_3

### ISSUE THREAD

**Issue by 1292917512** [wujsAct/DGCN_EL#2]
The s2_1 program has been running for 100 hours, tag: testa has been 625it, how many it is there or how long will it be running? Regarding S3_3, the folder generated/embeddings/word_ent_embs is not found, and the files dict.entity and entity_embeddings.npy are missing

**Comment by wujsAct** [comment]
You need to create an index to speed up the search process; I have updated the run.sh script, please follow the instructions. In fact, I have finished all the pre-process tasks, you can directly insert the feature files into MongoDB and then start to train the model.
