### ISSUE TITLE
step get_ent_linking_data.py

### ISSUE THREAD

**Issue by 1292917512** [wujsAct/DGCN_EL#3]
When the code runs to line 131 of load_entity_vector.py, the statement "old_id2ent = {old_ent2id[enti]:enti for enti in old_ent2id}" will report the error unhashable type:'list'. I have tried to modify the code, but the program is at line 152 Report an error

**Comment by wujsAct** [comment]
This project runs on Python 2.7. I did not test this code on Python 3.0. Can you paste the screenshot of your error?

**Comment by 1292917512** [comment]
![错误](https://user-images.githubusercontent.com/44597643/89856591-42dfdc80-dbcc-11ea-8e24-c2acbe794850.png)

**Comment by 1292917512** [comment]
![错误](https://user-images.githubusercontent.com/44597643/89856603-483d2700-dbcc-11ea-8819-0daad5566505.png)

**Comment by wujsAct** [comment]
I did not get this bug when I ran the file~

**Comment by 1292917512** [comment]
Problem has been solved
