### ISSUE TITLE
step：train_global_gen_elmo

### ISSUE THREAD

**Issue by 1292917512** [wujsAct/DGCN_EL#6]
The input parameter sent_lent_list of get_doc_sent_for_ments() in line 219 of the code is empty,
resulting in input_utils.py 21 line max function error
![image](https://user-images.githubusercontent.com/44597643/90810786-1ce9d300-e356-11ea-88d5-8e1f35749c6b.png)

which leads to the wrong choice of ignore and the corresponding file cannot be generated, resulting in the failure of subsequent code execution. I have been stuck here for a long time and have not found a solution. 
Can you help me? Thank you

**Comment by 1292917512** [comment]
I think it may be a file problem. Other files are downloaded from where you are. The file word_info.p is generated by myself. The md5 value is ab94a5720db1be0b5a541d138772f440

**Comment by 1292917512** [comment]
This is the size of some other files
-rwxrwxrwx 1 root root 775M Jul 21 18:33 crosswikis_wikipedia_p_e_m.txt
-rwxrwxrwx 1 root root  21M Aug 19 12:20 persons.txt
-rwxrwxrwx 1 root root  12G Sep 13  2017 textWithAnchorsFromAllWikipedia2014Feb.txt
-rwxrwxrwx 1 root root 4.3M Sep 13  2017 wiki_disambiguation_pages.txt
-rwxrwxrwx 1 root root 121M Sep 13  2017 wiki_name_id_map.txt
-rwxrwxrwx 1 root root 123M Aug 20 03:04 wiki_name_id_map_from_corpus.txt
-rwxrwxrwx 1 root root 254M Sep 13  2017 wiki_redirects.txt
-rwxrwxrwx 1 root root 602M Aug 22 10:26 word_info.p
-rwxrwxrwx 1 root root  11M Jul 27 19:25 word_wiki_freq.txt
-rwxrwxrwx 1 root root 749M Jul 21 20:39 yago_p_e_m.txt
-rwxrwxrwx 1 root root 3.4G Dec 11  2013 GoogleNews-vectors-negative300.bin
-rwxrwxrwx 1 root root 4.0M Aug  9 03:40 ent2id.p
-rwxrwxrwx 1 root root 124M Aug  9 03:32 ent_ent_feats.txt
-rwxrwxrwx 1 root root  32M Aug 20 09:38 ent_transE_embed.npy
-rwxrwxrwx 1 root root 621M Aug 20 09:39 ent_w2v_embed.npy
-rwxrwxrwx 1 root root 2.4G Aug 20 09:24 freebase-vectors-skipgram1000-en.bin.gz
-rwxrwxrwx 1 root root 2.3K Aug  9 03:34 stopwords.txt

I ran it again with python2.7 in unbuntu
I want to run this code completely, please help me, thank you very much

**Comment by xuan9864** [comment]
hello, do you solve this problem? Thank you!
